### ISSUE TITLE
Failed to compile due to " no type named 'type' in 'struct std::enable_if<false, nonstd::expected_lite::detail::enabler>'" from expected-lite

### ISSUE THREAD

**Issue by faizol** [Stiffstream/restinio-crud-example#1]
Hi,
I'm having a problem to compile this sample, and I believe this has something to do with this issue https://github.com/martinmoene/expected-lite/issues/32? The expected-lite and optional-lite have since been updated with samples from both repos can be normally compiled.

How should I go about to get this restinio sample compiled?

My system: Fedora 31
Steps : as in the README.md in the repo.
Error messages: 
restinio-crud-example/crud-example/request_processor.cpp:150:62:   required from here
/vcpkg/installed/x64-linux/include/restinio/third_party/expected-lite/expected.hpp:1624:16: error: no type named 'type' in 'struct std::enable_if<false, nonstd::expected_lite::detail::enabler>'
 1624 |     expected & operator=( nonstd::unexpected_type<G> const & error )
      |                ^~~~~~~~
/vcpkg/installed/x64-linux/include/restinio/third_party/expected-lite/expected.hpp:1636:16: error: no type named 'type' in 'struct std::enable_if<false, nonstd::expected_lite::detail::enabler>'
 1636 |     expected & operator=( nonstd::unexpected_type<G> && error )
 restinio/sample/restinio-crud-example/crud-example/request_processor.cpp:3:
/vcpkg/installed/x64-linux/include/restinio/third_party/expected-lite/expected.hpp: In instantiation of 'class nonstd::expected_lite::unexpected_type<crud_example::request_processing_failure_t>':
restinio-crud-example/crud-example/request_processor.cpp:156:5:   required from here
/vcpkg/installed/x64-linux/include/restinio/third_party/expected-lite/expected.hpp:980:5: error: no type named 'type' in 'struct std::enable_if<false, void>'
  980 |     swap( unexpected_type & other ) noexcept (
      |     ^~~~
make[2]: *** [crud-example/CMakeFiles/crud_example.dir/build.make:89: crud-example/CMakeFiles/crud_example.dir/request_processor.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:94: crud-example/CMakeFiles/crud_example.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by eao197** [comment]
Hi!

Thanks for reporting this.

As for now, I see the only way to solve this issue:

* fork restinio and replace `dev/restinio/third_party/expected-lite/expected.hpp` file to the [`expected.hpp` from expected-lite repository](https://github.com/martinmoene/expected-lite/blob/5e53c5f18cedb2273ce7c50c2d219b68b5754f05/include/nonstd/expected.hpp).
* fork vcpkg and modify RESTinio's portfile.cmake to point to a commit from your restinio's fork.

Then use your own vcpkg fork instead of original Microsoft's version for installing dependencies for restinio-crud-example.

Unfortunately, I have no time to fix this issue with expected-lite versions in RESTinio until the end of the week :(

**Comment by faizol** [comment]
Thanks for the help, really appreciate it. I got the example compiled by using the old expected-lite released (expected-lite-0.2.0).
